data:
  gpu: 0
  in_memory: 1
  num_workers: 12
dist:
  world_size: 1
logging:
  folder: /tmp/
  log_level: 0
lr:
  lr: 0.5
  lr_peak_epoch: 2
  lr_schedule_type: cyclic
resolution:
  res: 192
training:
  batch_size: 1024
  bn_wd: 0
  epochs: 100
  momentum: 0.9
  optimizer: sgd
  weight_decay: 5e-5
validation:
  lr_tta: true
  resolution: 256
